version: '2'

services:
    php:
        build: ./${PHP_VERSION}

        volumes_from:
            - source
        links:
            - db
            - memcached
        networks:
            - kant_network
        restart: unless-stopped
    web_server:
        build: ./${WEB_SERVER_TYPE}
        depends_on:
            - source
        volumes_from:
            - source
        ports:
            - '${INTERFACE}:80:80'
            - '${INTERFACE}:443:443'
            - '${INTERFACE}:3000:3000'
        links:
            - php
        networks:
            - kant_network
        restart: unless-stopped
    db:
        build: ./${DB_SERVER_TYPE}
        platform: linux/amd64
        volumes:
            - ./${DB_SERVER_TYPE}/init:/docker-entrypoint-initdb.d
        volumes_from:
            - source
        ports:
            - '${INTERFACE}:3306:3306'
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        command: mysqld --user=root --sql-mode=""
        networks:
            - kant_network
        restart: unless-stopped
    memcached:
        image: memcached:1.6.12-alpine
        volumes_from:
            - source
        ports:
            - '${INTERFACE}:11211:11211'
        networks:
            - kant_network
        restart: unless-stopped
    elk:
        image: sebp/elk
        ports:
            - "5601:5601"
            - "9200:9200"
            - "5044:5044"
        networks:
            - kant_network
    adminer:
        image: dockette/adminer:full
        links:
            - db:db
        ports:
            - '${INTERFACE}:8181:80'
        environment:
            UPLOAD: 1024M # upload_max_filesize, post_max_size
        networks:
            - kant_network
    source:
        image: alpine:latest
        volumes:
            - ./logs/${WEB_SERVER_TYPE}:/var/log/${WEB_SERVER_TYPE}
            - ./logs/php:/var/log/php
            - ./logs/db:/var/log/mysql
            - ./logs/memcached:/var/log/memcached
            - db:/var/lib/mysql
            - cache:/var/lib/memcached
            - ./www/html:/var/www/html
            - ${SITE_PATH}:/var/www/bitrix
#            - /etc/localtime:/etc/localtime/:ro
        networks:
            - kant_network

volumes:
    db:
        driver: local
    cache:
        driver: local

networks:
    kant_network:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 10.100.0.0/24
