version: '2'

services:
    php:
        build: ./${PHP_VERSION}

        volumes_from:
            - source
        links:
            - db
            - memcached
        networks:
            - kant_network
        restart: unless-stopped
    web_server:
        build: ./${WEB_SERVER_TYPE}
        depends_on:
            - source
        volumes_from:
            - source
        ports:
            - '${INTERFACE}:80:80'
            - '${INTERFACE}:443:443'
            - '${INTERFACE}:3000:3000'
            - '${INTERFACE}:8989:8989'
        links:
            - php
        networks:
            - kant_network
        restart: unless-stopped
    db:
        build: ./${DB_SERVER_TYPE}
        volumes:
            - ./${DB_SERVER_TYPE}/init:/docker-entrypoint-initdb.d
        volumes_from:
            - source
        ports:
            - '${INTERFACE}:3306:3306'
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        command: mysqld --user=root --sql-mode=""
        networks:
            - kant_network
        restart: unless-stopped
    memcached:
        image: memcached:1.6.12-alpine
        volumes_from:
            - source
        ports:
            - '${INTERFACE}:11211:11211'
        networks:
            - kant_network
        restart: unless-stopped
    redis:
        image: redis:6.2-alpine
        restart: always
        ports:
            - '6379:6379'
        command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
        volumes:
            - cache:/data
        networks:
            - kant_network
    rabbitmq:
        image: rabbitmq:3-management
        ports:
            - '5672:5672'
            - '15672:15672'
        volumes:
          - ./rabbitmq/data/:/var/lib/rabbitmq/
          - ./logs/rabbitmq:/var/log/rabbitmq/
          - ./rabbitmq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config
          - ./rabbitmq/rabbit.json:/etc/rabbitmq/rabbit.json
        links:
            - php
        networks:
          - kant_network
    elk:
        image: sebp/elk
        environment:
            node.name: elk
            ES_JAVA_OPTS: -Xms512m -Xmx512m
            # Bootstrap password.
            # Used to initialize the keystore during the initial startup of
            # Elasticsearch. Ignored on subsequent runs.
            ELASTIC_PASSWORD: ${ELASTIC_PASSWORD:-}
            # Use single node discovery in order to disable production mode and avoid bootstrap checks.
            # see: https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
            discovery.type: single-node
            LS_JAVA_OPTS: -Xms256m -Xmx256m
            LOGSTASH_INTERNAL_PASSWORD: ${LOGSTASH_INTERNAL_PASSWORD:-}
#        mem_limit: 4g
        volumes:
            - ./elk/logstash/20-input.conf:/etc/logstash/conf.d/20-input.conf
            - ./elk/logstash/30-output.conf:/etc/logstash/conf.d/30-output.conf
        ports:
            - "5601:5601"
            - "9200:9200"
            - "5044:5044"
        networks:
            - kant_network
    adminer:
        image: dockette/adminer:full
        links:
            - db:db
        ports:
            - '${INTERFACE}:8181:80'
        environment:
            UPLOAD: 1024M # upload_max_filesize, post_max_size
        networks:
            - kant_network
    source:
        image: alpine:latest
        volumes:
            - ./logs/${WEB_SERVER_TYPE}:/var/log/${WEB_SERVER_TYPE}
            - ./logs/php:/var/log/php
            - ./logs/db:/var/log/mysql
            - ./logs/memcached:/var/log/memcached
            - ./logs/bitrix:/var/log/bitrix
            - db:/var/lib/mysql
            - cache:/var/lib/memcached
            - ./tmp:/var/www
            - ./www/html:/var/www/html
            - ${SITE_PATH}:/var/www/bitrix
#            - /etc/localtime:/etc/localtime/:ro
        networks:
            - kant_network

volumes:
    db:
        driver: local
    cache:
        driver: local

networks:
    kant_network:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 10.100.0.0/24
